[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.7"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "/urp506"
  to = "https://xfliang.notion.site/FALL-24-URP-506-Planning-Methods-61df025314da4610864331cd46dca52a?pvs=4"
  status = 200
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/urp610"
  to = "https://xfliang.notion.site/FALL-24-URP-610-UT-401-Urban-Networks-1bcba1533a934578861584b1494db158?pvs=4"
  status = 200
  status = 301
  force = true # COMMENT: ensure that we always redirect
